# Docker Compose file for Raspberry Pi deployment using pre-built image
version: '3.8'

services:
  contract-crown:
    image: ${DOCKER_USERNAME:-contractcrown}/contract-crown:${VERSION:-latest}
    container_name: contract-crown
    restart: unless-stopped
    platform: linux/arm64
    environment:
      NODE_ENV: production
      PORT: 3000
      
      # Database configuration - connect to external MySQL
      DB_HOST: ${DB_HOST:-host.docker.internal}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME:-contract_crown}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-}
      
      # JWT configuration
      JWT_SECRET: ${JWT_SECRET:-contract-crown-jwt-secret-change-in-production}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-24h}
      
      # CORS configuration
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      
      # Rate limiting
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-900000}
      RATE_LIMIT_MAX_REQUESTS: ${RATE_LIMIT_MAX_REQUESTS:-100}
      
      # WebSocket configuration
      WS_HEARTBEAT_INTERVAL: ${WS_HEARTBEAT_INTERVAL:-25000}
      WS_HEARTBEAT_TIMEOUT: ${WS_HEARTBEAT_TIMEOUT:-60000}
      
      # Application settings
      MAX_PLAYERS_PER_GAME: ${MAX_PLAYERS_PER_GAME:-4}
      GAME_TIMEOUT_MS: ${GAME_TIMEOUT_MS:-1800000}
      
    ports:
      - "3000:3000"
    volumes:
      # Persistent data storage on Raspberry Pi
      - contract_crown_data:/app/data
      - contract_crown_logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "src/health-check.js"]
      timeout: 10s
      retries: 3
      start_period: 30s
      interval: 30s
    # Connect to host network to access MySQL on Pi
    network_mode: host

volumes:
  contract_crown_data:
    driver: local
  contract_crown_logs:
    driver: local